# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
rssFullContent = true

[footer]
since = 2024
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸŒŸ"
subtitle = "æŠ€æœ¯åšå®¢"

[sidebar.avatar]
enabled = true
local = false
src = "https://pub-3882fdd9f81f44b996a0eb4c32a8c257.r2.dev/black-saber.jpg"

[article]
math = false
readingTime = true
toc = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

# ä¸»é¡µå°éƒ¨ä»¶
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"
params.limit = 5

[[widgets.homepage]]
type = "categories"
params.limit = 10

[[widgets.homepage]]
type = "tag-cloud"
params.limit = 20

[[widgets.page]]
type = "toc"

[search]
enabled = true

[colorScheme]
toggle = true
default = "auto"

[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "Yikai-Liao/blog"
repoID = "R_kgDOOcmk4Q"
category = "Announcements"
categoryID = "DIC_kwDOOcmk4c4CpR8x"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "zh-CN"